export enum SECTION {
  HOME = 'HOME',
  MESSENGER = 'MESSENGER',
  FINDPEOPLE = 'FINDPEOPLE',
  ACTIVITYFEED = 'ACTIVITYFEED',
  SELF = 'SELF',
  NEW_POST = 'NEW_POST',
  REELS = 'REELS',
  SEARCH = 'SEARCH',
}
